name = "cardumen/sandbox"
version = "0.0.0"
compiler = "v1.1.21"
plutus = "v3"
license = "Apache-2.0"
description = "Compile sandbox for Cardumen Forge benchmark"

[repository]
user = "eval"
project = "aiken_sandbox"
platform = "github"

[[dependencies]]
name = "aiken-lang/stdlib"
version = "v3.0.0"
source = "github"

[config]
